module.exports = {
  important: true,
  prefix: "tw-",
  purge: [
    "./src/**/*.vue",
    "./src/**/*.js",
    "./src/**/*.md",
    "./src/**/*.html",
    "./src/**/*.css",
    "./src/**/*.{js,jsx,ts,tsx,vue}",
  ],
  content: [
    "./src/**/*.vue",
    "./src/**/*.js",
    "./src/**/*.md",
    "./src/**/*.html",
    "./src/**/*.css",
    "./src/**/*.{js,jsx,ts,tsx,vue}",
  ],
  darkMode: "class",
  variants: {
    extend: {
      borderStyle: ["responsive", "hover"],
      borderWidth: ["responsive", "hover"],
    },
  },
  plugins: [
    require("postcss-import"),
    require("tailwindcss"),
    require("autoprefixer"),
  ],
  theme: {
    screens: {
      xs: "375px",
      ss: "540px",
      sm: "769px",
      md: "1024px",
      lg: "1216px",
      xl: "1616px",
      "2xl": "1890px",
    },
    extend: {
      blur: {
        xs: "1px",
      },
      gridTemplateRows: {
        "xs-card": "160px",
      },
      gridTemplateColumns: {
        "xs-card": "90px 1fr",
        "ss-card": "120px 1fr",
        "sm-card": "160px 1fr",
      },
      colors: {
        "rd-main-dark": "#000024",
        "rd-main": "#f7f0ff",
        "rd-highlight": "rgba(116, 85, 239, 1)",
        "rd-highlight-dark": "rgba(182, 123, 238, 1)",
        "rd-high": "rgba(51, 47, 101, 1)",
        "rd-high-dark": "rgba(166, 242, 249, 1)",
        "rd-subtext": "rgba(98, 103, 149, 1)",
        "rd-subtext-dark": "#626795",
        "rd-signbutton-1": "#7A27CB",
        "rd-signbutton-2": "#E387C1",
        "rd-border-fancy-table": "rgba(98, 103, 149, 0.2)",
        "rd-border-fancy": "rgba(98, 103, 149, 0.2)",
        "rd-border-fancy-dark": "#33375F",
        "rd-title-white-dark": "#A7A9BA",
        "rd-white-opacity": "rgba(255, 255, 255, 0.5)",
        "rd-footer": "#d8dbf1",
        "rd-border-card": "#8d42c3",
        "rd-border-card-dark": "#a56cd5",
        "rd-separator-card": "rgba(64, 57, 136, 0.5)",
        "rd-content-card-dark": "#0E1052",
        "rd-content-alert-card": "#EDEDF3",
        "rd-transparent-white-card": "#ffffff9e",
        "rd-transparent-dark-card": "#000000c9",
        "rd-transparent-high-white-card": "#ffffffcc",
        "rd-transparent-high-dark-card": "#000000ab",
        "rd-pink": "#FBD0FF",
      },
      zIndex: {
        "1": "-1",
      },
      minWidth: {
        "128": "40rem",
      },
    },
  },
}
